project_id = "txnakwcjejjgqtevnlle"

[functions.check-rss]
verify_jwt = false

[functions.verify-password]
verify_jwt = false

[functions.delete-news]
verify_jwt = false

[functions.validate-token]
verify_jwt = false
